admin-paths:
  paths:
    - 
      uri: "/api/v1/users"
      method: "POST"
    - 
      uri: "/api/v1/users/createAccount/{1}[1-9]+[0-9]*"
      method: "POST"
    - 
      uri: "/api/v1/users"
      method: "GET"