admin-paths:
  paths:
    - 
      uri: "/user/save"
      method: "POST"
    - 
      uri: "/user/saveaccount/{1}[1-9]+[0-9]*"
      method: "POST"
    - 
      uri: "/user/users"
      method: "GET"