spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri:
          lb://user-service
        predicates:
          - Path=/api/v1/users/**
        filters:
          - AuthFilter
      - id: account-service
        uri:
          lb://account-service
        predicates:
        - Path=/api/v1/accounts/**
      - id: transaction-service
        uri:
          lb://transaction-service
        predicates:
        - Path=/api/v1/transactions/**
      - id: auth-service
        uri:
          lb://auth-service
        predicates:
        - Path=/api/v1/auths/**
                