CREATE TABLE USER ( 
   ID_USER INTEGER PRIMARY KEY AUTO_INCREMENT, 
   NAMEUSER VARCHAR(50) NOT NULL UNIQUE,
   EMAIL VARCHAR(50) NOT NULL UNIQUE,
   LIMIT_DAILY INTEGER DEFAULT 3, 
   LAST_DATE DATE DEFAULT SYSDATE, 
   PASSWORD VARCHAR(50) NOT NULL,
   ROLE VARCHAR(10) NOT NULL
);