CREATE TABLE ACCOUNT ( 
   ID_ACCOUNT INTEGER PRIMARY KEY AUTO_INCREMENT, 
   NUMER_ACCOUNT VARCHAR(20) NOT NULL,
   CURRENCY VARCHAR(3) NOT NULL, 
   AMOUNT INTEGER NOT NULL, 
   ID_USER INTEGER NOT NULL
);